version: "3.8"

services:
  nextjs:
    build: .
    container_name: backend_nextjs_mysql
    restart: unless-stopped
    ports:
      - "3333:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}